import "../engine/testAllocation";
import "../debt/testDebtProjection";
import "./testPlannerStateHardening";
import "./testStressScenarios";
import "./testAbuseScenarios";
import "./testAprMath";
import "../payCycle/testPayCycle";
import "../debt/testProjectionAccuracy";
import "../debt/testAmortizationSchedule";
import "../debt/testComputeMilestones";
import "../debt/testComputeStreak";
import "./testFinalLaunchRegression";
import "./testV11Regression";
import "./testFullAppRegression";
import "./testTimelineRegression";
import "./testMultiCycleTimelineRegression";
import "./testRecommendedActionsRegression";
import "./testForecastRegression";
import "./testDebtMathRegression";
import "./testSubscriptionGating";
import "./testPayCycleHistoryRegression";
import "./testSafeStorage";

console.log("✅ All regression tests passed.");