import { runCases } from './driver';
runCases([
  { id: 'D1-3', target: 'packages/core/utils/percentComplete.ts', append: '\nexport const __d13 = (raw: string) =>\n  parseAmountField(\n    raw,\n  ) ?? 0;\n', cmd: ['npx', 'tsx', 'scripts/check-amount-collapse.ts'], want: /collapses a parsed amount to 0/, wantExit: 1 },
  { id: 'D1-4', target: 'apps/rn/src/components/plan/AffordabilityCard.tsx', append: '\nexport const __a = parseAmountField(amount) ?? 0;\nexport const __b = parseAmountField(amount) ?? 0;\n', cmd: ['npx', 'tsx', 'scripts/check-amount-collapse.ts'], want: /amount-collapse: 2 problem/, wantExit: 1 },
  { id: 'D1-6', target: 'packages/core/utils/percentComplete.ts', append: '\nexport const __d16 = (x: number) =>\n  Math.round(\n    x * 100,\n  ) / 100;\n', cmd: ['npx', 'tsx', 'scripts/check-rounding.ts'], want: /95 inline money-rounding/, wantExit: 1 },
  { id: 'R3', target: 'packages/core/utils/percentComplete.ts', append: '\nexport const __r3 = (x: number) =>\n  Math.round(\n    x * 100,\n  ) / 100;\n', cmd: ['npx', 'tsx', 'scripts/check-rounding.ts'], want: /percentComplete.ts:41/, wantExit: 1 },
  { id: 'R4', target: 'apps/rn/src/components/plan/AffordabilityCard.tsx', append: '\nexport const __r4a = parseAmountField(amount);\nexport const __r4b = 0 ?? 0;\n', cmd: ['npx', 'tsx', 'scripts/check-amount-collapse.ts'], want: /amount-collapse: 0 site/, wantExit: 0 },
  { id: 'T2', target: 'apps/rn/src/components/plan/AffordabilityCard.tsx', append: '\nexport const __t2 = fn(parseAmountField(amount), other ?? 0);\n', cmd: ['npx', 'tsx', 'scripts/check-amount-collapse.ts'], want: /amount-collapse: 0 site/, wantExit: 0 },
  { id: 'T3', target: 'apps/rn/src/components/plan/AffordabilityCard.tsx', append: '\nexport const __t3 = parseAmountField({ raw: amount }) ?? 0;\n', cmd: ['npx', 'tsx', 'scripts/check-amount-collapse.ts'], want: /collapses a parsed amount to 0/, wantExit: 1 },
  { id: 'T3b', target: 'packages/core/utils/percentComplete.ts', append: '\nexport const __t3b = (x: number) => Math.round(fn({ a: x }) * 100) / 100;\n', cmd: ['npx', 'tsx', 'scripts/check-rounding.ts'], want: /95 inline money-rounding/, wantExit: 1 },
  { id: 'T8', target: 'apps/rn/src/store/analysisSelectors.ts', append: '\nexport const __t8 = (rows: { id: string }[], id: string) =>\n  rows.findIndex((r) => {\n    return r.id === id;\n  });\n', cmd: ['npx', 'tsx', 'scripts/check-store-id-writes.ts'], want: /no bare id-keyed row edits/, wantExit: 0 },
  { id: 'T8b', target: 'apps/rn/src/store/analysisSelectors.ts', append: '\nexport const __t8b = (rows: { id: string }[], id: string) =>\n  rows.map((r) => (r.id === id ? r : r));\n', cmd: ['npx', 'tsx', 'scripts/check-store-id-writes.ts'], want: /bare .x.id === id. comparison|outside a lookup/, wantExit: 1 },
  { id: 'N-5', target: 'apps/rn/src/store/analysisSelectors.ts', append: '\nexport const __n5 = (rows: { id: string }[], id: string) =>\n  rows.findIndex(\n    (r) => r.id === id,\n  );\n', cmd: ['npx', 'tsx', 'scripts/check-store-id-writes.ts'], want: /no bare id-keyed row edits/, wantExit: 0 },
]);
